{% set name = "napari-tomoslice" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-tomoslice-{{ version }}.tar.gz
  sha256: 3c8bc659df18e4eaebb975a3a85714ee087c78569fc1bc3bc3c44e399f878bcc

build:
  entry_points:
    - napari-tomoslice = napari_tomoslice.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - mrcfile
    - napari ==0.4.12
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >={{ python_min }}
    - typer

test:
  imports:
    - napari_tomoslice
  commands:
    - pip list
    - pip check
    - napari-tomoslice --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alisterburt/napari-tomoslice
  summary: A napari plugin for interacting with electron cryotomograms
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alisterburt
    - goanpeca
    - jaimergp
